### ISSUE TITLE
Error running composer install when following README instructions.

### ISSUE THREAD

**Issue by chrisharrison** [prooph/micro-do#10]
When running the second instruction under 'Shared package' of the README:

`docker run --rm -it --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK --volume $(pwd):/app prooph/composer:7.1 install`

The following composer error occurs:

`The requested package prooph/common 4.0.x-dev exists as prooph/common[3.x-dev, dev-master, v1.0, v1.1, v1.2, v1.3, v1.4, v1.5, v2.0, v2.1, v2.2, v3.0, v3.0.1, v3.1, v3.2, v3.2.1, v3.3, v3.3.1, v3.4, v3.5, v3.5.1, v3.5.2, v3.5.3, v3.5.4, v3.5.5, v3.6, v3.7, v3.7.1, v4.0.0, v4.0.0-beta1, v4.0.0-beta2, v4.1.0] but these are rejected by your constraint.`

I've temporarily solved this issue for myself by modifying composer.json from:
`"prooph/common": "4.0.x-dev"`

to:
`"prooph/common": "^4.1.0"`

**Comment by prolic** [comment]
updated in master now, thanks for reporting
