### ISSUE TITLE
question

### ISSUE THREAD

**Issue by michabbb** [prooph/micro-do#11]
hi,

how does nginx know the hostnames? i guess there is something i don´t see in this docker/nginx config...

https://github.com/prooph/micro-do/blob/master/gateway/sites-enabled/www.conf#L24

btw.... great work!

**Comment by bweston92** [comment]
Docker compose will set up host name mapping in the container, the spec can be found https://github.com/prooph/micro-do/blob/master/docker-compose.yml#L21

**Comment by michabbb** [comment]
@bweston92 does this docker version no longer need "link" as an option ? maybe this is the missing part here ;)

**Comment by codeliner** [comment]
yep, what you define as service name in the compose file is added as host name to the default network created by docker
Hence, containers in the same network can "see each other"

**Comment by michabbb** [comment]
Okay, many thanks for clarification :)
