### ISSUE TITLE
A stream with name user_stream could not be found

### ISSUE THREAD

**Issue by sandrokeil** [prooph/micro-do#2]
If I want to create another user, I get the following error:

```
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "NOTICE: PHP message: [UserWriteService.Error] Prooph\EventStore\Exception\StreamNotFound: A stream with name user_stream could not be found in /var/www/vendor/prooph/event-store/src/Exception/StreamNotFound.php:21"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "Stack trace:"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#0 /var/www/vendor/prooph/pdo-event-store/src/PostgresEventStore.php(279): Prooph\EventStore\Exception\StreamNotFound::with(Object(Prooph\EventStore\StreamName))"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#1 /var/www/vendor/prooph/micro/src/Kernel.php(185): Prooph\EventStore\Pdo\PostgresEventStore->load(Object(Prooph\EventStore\StreamName), 1, 9223372036854775807, Object(Prooph\EventStore\Metadata\MetadataMatcher))"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#2 /var/www/vendor/prooph/micro/src/Kernel.php(93): Prooph\Micro\Kernel\loadEvents(Object(Prooph\EventStore\StreamName), Object(Prooph\EventStore\Metadata\MetadataMatcher), Object(Closure))"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#3 /var/www/vendor/prooph/micro/src/Kernel.php(152): Prooph\Micro\Kernel\{closure}(Array)"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#4 [internal function]: Prooph\Micro\Kernel\{closure}(Array, Object(Closure))"
php-user-write_1        | [23-Jan-2017 21:23:05] WARNING: [pool www] child 8 said into stderr: "#5 /var/www/vendor/prooph/micro/src/Kernel.php(153): array_..."
```

**Comment by codeliner** [comment]
@sandrokeil any idea why? Are you able to debug? prooph/micro are only a few LOC, shouldn't be that hard

**Comment by prolic** [comment]
I think you use SingleStreamStrategy and therefore the stream has to be
created manually upfront.

Sascha-Oliver Prolic

2017-01-25 3:08 GMT+08:00 Alexander Miertsch <notifications@github.com>:

**Comment by sandrokeil** [comment]
Yes, the user write service uses a `PostgresSimpleStreamStrategy` so should we change it or add a definition to the `initdb.d` scripts?

**Comment by prolic** [comment]
both is possible, @codeliner what do you prefer?

**Comment by codeliner** [comment]
SimpleStreamStrategy !== SingleStreamStrategy

A `SimpleStreamStrategy` is used and I had no problems with it but I only tested with one user. @sandrokeil you get the error when you try to create a second user, or what?
Maybe we have another problem here not directly related to the stream strategy used?

**Comment by prolic** [comment]
Don't use SimpleStreamStrategy for event sourcing!!! Only aggregate or single stream.

**Comment by sandrokeil** [comment]
> you get the error when you try to create a second user, or what?

Yes and I don't modified the source code. Was simply testing the app yesterday.

**Comment by codeliner** [comment]
ok, so I guess we have a strange bug here. Can you try to find the root of the issue? Why does the event store throw the exception. The `user_stream` must be there otherwise creating the first user would fail, too.

**Comment by sandrokeil** [comment]
I will take a look, the first user was or is created.

**Comment by codeliner** [comment]
great, thank you

**Comment by codeliner** [comment]
Tried it myself and got the same error...

@prolic This is the root of the error: https://github.com/prooph/micro/blob/master/src/Kernel.php#L169

Question is: Should we warp it in a try ... catch or change the EventStore::load method? Exceptions are very expensive due to the stack trace and should only be used for real errors. In this case the stream exists (user_stream) but `load` does not find events for a new user of course.

**Comment by prolic** [comment]
Assign to me, i will fix this

Am 26.01.2017 04:56 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by codeliner** [comment]
@prolic good job, your bugfix solved the issue

**Comment by dhirajpatra** [comment]
Anybody can help with an example for MySqlSingleStreamStrategy. So that only a single aggregate or event source table create. Thanks
